version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "4001:4001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth
      - JWT_SECRET=pikachu
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    ports:
      - "4003:4003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/order
      - JWT_SECRET=pikachu
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

